services:
  - type: web
    name: idg-questionbank
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:+HCTFg8S1g7JFSiqL3x1PI4bgLYicEd7BGaV/+WSJXs=
      - key: MOODLE_URL
        value: https://elearning.cadt.edu.kh
      - key: MOODLE_TOKEN
        value: c557108b2a03ca8cbe7e49469f8d3f63
      - key: MOODLE_SERVICE
        value: qapi

